// Creative Production — Ad format registry (PURE, no I/O; unit-tested by scripts/check-cp-ad-formats.ts).
// The canonical, verified (2026) list of platform ad sizes the compositor renders to. Dimensions are
// VERIFIED against Meta / Google docs (see each `source`) and must not be edited casually — the px are the
// contract the image pipeline and QA measure against. Safe zones are fractions (0..1) of each edge that
// text/logo must stay clear of. type-only import -> erased at runtime, so this file stays dependency-free.
import type { AdFormat } from "@/lib/creative-production/types";

export const AD_FORMATS: AdFormat[] = [
  // ---------- Meta (Facebook / Instagram) ----------
  {
    id: "meta-feed-1x1",
    platform: "meta",
    name: "Meta Feed Square",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    purpose: "Facebook + Instagram feed square. Safe cross-placement default.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Primary text ~125 chars before truncation; headline ~40 chars.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://www.facebook.com/business/ads-guide",
  },
  {
    id: "meta-feed-4x5",
    platform: "meta",
    name: "Meta Feed Vertical",
    width: 1080,
    height: 1350,
    aspectRatio: "4:5",
    purpose: "Feed vertical. Tallest allowed in-feed; best in-feed performer (most screen real estate).",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Primary text ~125 chars; headline ~40 chars. Keep key visual centred.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://www.facebook.com/business/ads-guide",
  },
  {
    id: "meta-story-9x16",
    platform: "meta",
    name: "Meta Stories / Reels",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    purpose: "Full-screen Stories and Reels on Facebook + Instagram.",
    // Unified Mar-2026 safe zone: UI chrome eats the top 14% and bottom 35%; sides 6%.
    safeZone: { top: 0.14, right: 0.06, bottom: 0.35, left: 0.06 },
    textConstraints: "Keep text + logo inside the safe zone; UI covers top 14% and bottom 35%.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://www.facebook.com/business/help/980593475366490",
  },
  {
    id: "meta-link-1.91x1",
    platform: "meta",
    name: "Meta Link / Landscape",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    purpose: "Landscape link ad (feed, right column, audience network). Cross-platform with Google landscape.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Headline ~40 chars; link description ~30 chars.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://www.facebook.com/business/ads-guide",
  },

  // ---------- Google (Responsive Display + uploaded display) ----------
  {
    id: "google-rda-landscape",
    platform: "google",
    name: "Google RDA Landscape",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    purpose: "Responsive Display Ad landscape marketing image (1.91:1).",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "No text overlay required (RDA supplies headline/description as fields).",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/7005917",
  },
  {
    id: "google-rda-square",
    platform: "google",
    name: "Google RDA Square",
    width: 1200,
    height: 1200,
    aspectRatio: "1:1",
    purpose: "Responsive Display Ad square marketing image (1:1).",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "No text overlay required (RDA supplies headline/description as fields).",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/7005917",
  },
  {
    id: "google-rda-portrait",
    platform: "google",
    name: "Google RDA Portrait",
    width: 1200,
    height: 1500,
    aspectRatio: "4:5",
    purpose: "Responsive Display Ad portrait marketing image (4:5).",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "No text overlay required (RDA supplies headline/description as fields).",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/7005917",
  },
  {
    id: "google-display-300x250",
    platform: "google",
    name: "Medium Rectangle",
    width: 300,
    height: 250,
    aspectRatio: "6:5",
    purpose: "Uploaded display banner. Highest-inventory display unit ('medium rectangle').",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Very small canvas: one short headline + logo, minimal body.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-336x280",
    platform: "google",
    name: "Large Rectangle",
    width: 336,
    height: 280,
    aspectRatio: "6:5",
    purpose: "Uploaded display banner ('large rectangle').",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Small canvas: short headline + logo, minimal body.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-728x90",
    platform: "google",
    name: "Leaderboard",
    width: 728,
    height: 90,
    aspectRatio: "364:45",
    purpose: "Uploaded display banner ('leaderboard'), top/bottom of page.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Wide + short strip: logo left, one line of copy, CTA right.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-300x600",
    platform: "google",
    name: "Half Page",
    width: 300,
    height: 600,
    aspectRatio: "1:2",
    purpose: "Uploaded display banner ('half page' / large skyscraper). High viewability.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Tall column: stacked headline, visual, CTA.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-160x600",
    platform: "google",
    name: "Wide Skyscraper",
    width: 160,
    height: 600,
    aspectRatio: "4:15",
    purpose: "Uploaded display banner ('wide skyscraper'), page sidebar.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Narrow + tall: logo top, minimal stacked copy, CTA bottom.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-970x250",
    platform: "google",
    name: "Billboard",
    width: 970,
    height: 250,
    aspectRatio: "97:25",
    purpose: "Uploaded display banner ('billboard'), premium top-of-page unit.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Wide hero strip: room for headline + subhead + CTA.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-320x50",
    platform: "google",
    name: "Mobile Banner",
    width: 320,
    height: 50,
    aspectRatio: "32:5",
    purpose: "Uploaded display banner ('mobile leaderboard'), anchored on mobile web.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Tiny strip: logo + one very short line + CTA.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
  {
    id: "google-display-320x100",
    platform: "google",
    name: "Large Mobile Banner",
    width: 320,
    height: 100,
    aspectRatio: "16:5",
    purpose: "Uploaded display banner ('large mobile banner'), double-height mobile unit.",
    safeZone: { top: 0.05, right: 0.05, bottom: 0.05, left: 0.05 },
    textConstraints: "Short strip: logo + one short headline + CTA.",
    exportFormat: "png",
    version: "2026-07",
    source: "https://support.google.com/google-ads/answer/1722096",
  },
];

// Look up one format by id. Returns undefined for an unknown id (never throws, never invents).
export function getFormat(id: string): AdFormat | undefined {
  return AD_FORMATS.find((f) => f.id === id);
}

// Default generation sets. META_DEFAULT_SET is the cross-platform default the pipeline seeds:
// 1080x1080, 1080x1350, 1080x1920, 1200x628 (the four Meta formats; the 1200x628 also serves Google
// landscape). GOOGLE_DEFAULT_SET is the RDA trio plus the highest-traffic uploaded display units.
export const META_DEFAULT_SET: AdFormat[] = [
  "meta-feed-1x1",
  "meta-feed-4x5",
  "meta-story-9x16",
  "meta-link-1.91x1",
].map((id) => getFormat(id)!);

export const GOOGLE_DEFAULT_SET: AdFormat[] = [
  "google-rda-landscape",
  "google-rda-square",
  "google-rda-portrait",
  "google-display-300x250",
  "google-display-728x90",
  "google-display-300x600",
  "google-display-160x600",
].map((id) => getFormat(id)!);
