// Creative Production — Static-ad concept format library (PURE, no I/O; unit-tested by
// scripts/check-cp-concept-formats.ts). ~70 archetypes: the default palette of static-ad layouts the
// strategy engine ranks and the compositor fills. Each entry is awareness-stage tagged so the engine can
// match a concept to where the audience is in the funnel. type-only import -> erased at runtime.
//
// SOURCE-OF-TRUTH NOTE: If a user-supplied Creative Format Library is added later, it becomes the source of
// truth (load-if-present) — do NOT overwrite this default. This list is the fallback the pipeline uses when
// no user library is loaded.
import type { ConceptFormat } from "@/lib/creative-production/types";

export const CONCEPT_FORMATS: ConceptFormat[] = [
  { id: "before-after", name: "Before/After", awarenessStage: "solution", structure: "Split frame: 'before' state on the left, improved 'after' state on the right.", textSlots: ["headline", "cta"], visualPattern: "Two side-by-side scenes of the same subject showing a visible change the product drives.", bestFor: "Products with a demonstrable, visual transformation." },
  { id: "problem-solution", name: "Problem/Solution", awarenessStage: "problem", structure: "Name the pain up top, present the product as the fix below.", textSlots: ["headline", "body", "cta"], visualPattern: "A frustrated moment resolving into a calm one once the product appears.", bestFor: "Audiences who feel the problem but do not know the fix." },
  { id: "five-star-review", name: "Five-Star Review", awarenessStage: "most_aware", structure: "A single glowing review quote anchored by five stars.", textSlots: ["quote", "rating", "cta"], visualPattern: "Product beside a large 5-star rating and a short verbatim customer line.", bestFor: "Closing warm buyers with concentrated social proof." },
  { id: "customer-testimonial", name: "Customer Testimonial", awarenessStage: "most_aware", structure: "A named customer, their photo, and their result in their words.", textSlots: ["quote", "body", "cta"], visualPattern: "Real customer portrait with a highlighted pull-quote about their outcome.", bestFor: "Building trust with a relatable, specific success story." },
  { id: "ugc-quote", name: "UGC Quote", awarenessStage: "product", structure: "A raw user-generated-style caption over an authentic phone photo.", textSlots: ["quote", "cta"], visualPattern: "Casual, unpolished UGC shot of the product in real use with an overlaid quote.", bestFor: "Feeds where native, non-ad-looking creative outperforms." },
  { id: "product-hero", name: "Product Hero", awarenessStage: "product", structure: "The product, large and centred, as the single focal point.", textSlots: ["headline", "cta"], visualPattern: "Clean studio hero shot of the product on a brand-coloured background.", bestFor: "A recognisable product that sells on its own look." },
  { id: "product-benefit", name: "Product+Benefit", awarenessStage: "product", structure: "Product on one side, its single biggest benefit called out on the other.", textSlots: ["headline", "subhead", "cta"], visualPattern: "Product shot with one benefit label and a supporting icon or line.", bestFor: "Leading with the one reason this product wins." },
  { id: "product-offer", name: "Product+Offer", awarenessStage: "most_aware", structure: "Product paired with a bold discount or offer badge.", textSlots: ["headline", "offer", "cta"], visualPattern: "Hero product with a prominent offer flash (e.g. percentage off) beside it.", bestFor: "Driving action from buyers already considering the product." },
  { id: "product-vs-alternative", name: "Product vs Alternative", awarenessStage: "product", structure: "This product on one side vs a generic alternative on the other.", textSlots: ["headline", "body", "cta"], visualPattern: "Two products framed head-to-head with the winner visually favoured.", bestFor: "Category switchers weighing this against what they use now." },
  { id: "us-vs-them", name: "Us vs Them", awarenessStage: "solution", structure: "Brand approach vs the old/competitor way, framed as a clear contrast.", textSlots: ["headline", "body", "cta"], visualPattern: "Contrast layout: 'them' dull and cluttered, 'us' clean and confident.", bestFor: "Positioning against an incumbent way of doing things." },
  { id: "myth-vs-reality", name: "Myth vs Reality", awarenessStage: "problem", structure: "State a common myth, then correct it with the reality.", textSlots: ["headline", "body", "cta"], visualPattern: "Two-panel 'Myth' vs 'Reality' contrast with a struck-through misconception.", bestFor: "Categories clouded by a widespread false belief." },
  { id: "3-reasons-why", name: "3 Reasons Why", awarenessStage: "product", structure: "Three numbered reasons to choose the product, stacked.", textSlots: ["headline", "body", "cta"], visualPattern: "Product beside three numbered benefit rows with small icons.", bestFor: "Summarising the core case in a scannable list." },
  { id: "5-reasons-why", name: "5 Reasons Why", awarenessStage: "product", structure: "Five numbered reasons to choose the product, stacked.", textSlots: ["headline", "body", "cta"], visualPattern: "Product beside five compact numbered benefit rows.", bestFor: "Products with several distinct, defensible benefits." },
  { id: "ingredient-spotlight", name: "Ingredient Spotlight", awarenessStage: "product", structure: "Feature one hero ingredient and what it does.", textSlots: ["headline", "body", "cta"], visualPattern: "Close-up of a key ingredient next to the product with a short claim.", bestFor: "Formulation-led products where an ingredient is the hook." },
  { id: "benefit-breakdown", name: "Benefit Breakdown", awarenessStage: "product", structure: "Map product parts/features to the benefit each delivers.", textSlots: ["headline", "body", "cta"], visualPattern: "Product with call-out lines linking features to their benefits.", bestFor: "Explaining why the design or formula matters." },
  { id: "founder-message", name: "Founder Message", awarenessStage: "solution", structure: "A direct, personal note from the founder on why this exists.", textSlots: ["headline", "body", "cta"], visualPattern: "Founder portrait with a handwritten-style personal message.", bestFor: "Mission-led brands building an authentic connection." },
  { id: "expert-quote", name: "Expert Quote", awarenessStage: "solution", structure: "An authority figure endorses the mechanism or product.", textSlots: ["quote", "body", "cta"], visualPattern: "Expert portrait with credentials and a short authoritative quote.", bestFor: "Categories where credibility unlocks consideration." },
  { id: "social-proof", name: "Social Proof", awarenessStage: "most_aware", structure: "Aggregate proof: customer count, rating average, press badges.", textSlots: ["headline", "stat", "cta"], visualPattern: "Product surrounded by proof markers: star average, review count, logos.", bestFor: "Reassuring buyers that many others already chose it." },
  { id: "review-wall", name: "Review Wall", awarenessStage: "most_aware", structure: "A grid of short review snippets forming a wall of praise.", textSlots: ["quote", "rating", "cta"], visualPattern: "Multiple stacked review cards, each with stars and a one-line quote.", bestFor: "Volume of proof for a well-reviewed product." },
  { id: "rating-card", name: "Rating Card", awarenessStage: "most_aware", structure: "A single large star rating with the average score.", textSlots: ["rating", "stat", "cta"], visualPattern: "Oversized star rating and numeric average beside the product.", bestFor: "One-glance credibility for a high-rated product." },
  { id: "comparison-table", name: "Comparison Table", awarenessStage: "product", structure: "A feature checklist table: us vs the alternatives.", textSlots: ["headline", "body", "cta"], visualPattern: "Tick/cross comparison grid with the brand column fully ticked.", bestFor: "Feature-led categories where the brand out-specs rivals." },
  { id: "did-you-know", name: "Did You Know", awarenessStage: "unaware", structure: "Open with a surprising fact that reframes the category.", textSlots: ["headline", "stat", "cta"], visualPattern: "Bold factual statement on a clean background with a supporting visual.", bestFor: "Cold audiences who do not yet know they have a problem." },
  { id: "educational", name: "Educational", awarenessStage: "unaware", structure: "Teach one useful thing, positioning the brand as the guide.", textSlots: ["headline", "body", "cta"], visualPattern: "Simple explainer graphic or diagram illustrating one idea.", bestFor: "Top-of-funnel value-first content that builds authority." },
  { id: "faq", name: "FAQ", awarenessStage: "product", structure: "Answer the single most common pre-purchase question.", textSlots: ["headline", "body", "cta"], visualPattern: "A 'Q:' / 'A:' layout beside the product.", bestFor: "Removing a known blocker that stalls the purchase." },
  { id: "objection-handling", name: "Objection Handling", awarenessStage: "most_aware", structure: "Name the top objection, then dismantle it.", textSlots: ["headline", "body", "cta"], visualPattern: "The objection as a struck-through worry, answered by a confident reply.", bestFor: "Warm buyers held back by one specific doubt." },
  { id: "price-anchor", name: "Price Anchor", awarenessStage: "most_aware", structure: "Anchor against a higher reference price to show value.", textSlots: ["headline", "offer", "cta"], visualPattern: "Struck-through anchor price beside the actual lower price.", bestFor: "Value framing when the real price beats expectations." },
  { id: "bundle", name: "Bundle", awarenessStage: "most_aware", structure: "Show the multi-item bundle and its combined saving.", textSlots: ["headline", "offer", "cta"], visualPattern: "Grouped product set with a 'bundle and save' badge.", bestFor: "Raising average order value with a packaged deal." },
  { id: "limited-offer", name: "Limited Offer", awarenessStage: "most_aware", structure: "A time-bound offer with urgency.", textSlots: ["headline", "offer", "cta"], visualPattern: "Product with a countdown or 'ends soon' urgency flash.", bestFor: "Pushing fence-sitters to act now." },
  { id: "new-product", name: "New Product", awarenessStage: "product", structure: "Announce the launch and what is new about it.", textSlots: ["headline", "subhead", "cta"], visualPattern: "Hero product with a prominent 'NEW' badge.", bestFor: "Launches and restocks to an interested audience." },
  { id: "best-seller", name: "Best Seller", awarenessStage: "most_aware", structure: "Lead with best-seller status as proof of demand.", textSlots: ["headline", "stat", "cta"], visualPattern: "Product with a 'best seller' banner and a demand stat.", bestFor: "Leveraging popularity to reassure new buyers." },
  { id: "gift", name: "Gift", awarenessStage: "most_aware", structure: "Frame the product as the ideal gift for someone.", textSlots: ["headline", "body", "cta"], visualPattern: "Product styled as a gift, wrapped or in a giftable setting.", bestFor: "Gifting occasions and recipient-led purchases." },
  { id: "seasonal", name: "Seasonal", awarenessStage: "most_aware", structure: "Tie the product to a season, holiday, or moment.", textSlots: ["headline", "offer", "cta"], visualPattern: "Product in a seasonally themed scene with matching motifs.", bestFor: "Time-sensitive seasonal and holiday pushes." },
  { id: "problem-awareness", name: "Problem Awareness", awarenessStage: "problem", structure: "Dramatise the problem so the viewer recognises it in themselves.", textSlots: ["headline", "body", "cta"], visualPattern: "A vivid depiction of the pain point, product held back for later.", bestFor: "Making a latent problem feel real and urgent." },
  { id: "solution-awareness", name: "Solution Awareness", awarenessStage: "solution", structure: "Introduce the category of solution and why it works.", textSlots: ["headline", "body", "cta"], visualPattern: "The mechanism or approach illustrated simply, product as the example.", bestFor: "Audiences aware of the problem, weighing solution types." },
  { id: "product-awareness", name: "Product Awareness", awarenessStage: "product", structure: "Introduce this specific product as the solution to reach for.", textSlots: ["headline", "subhead", "cta"], visualPattern: "Confident product hero with a one-line positioning statement.", bestFor: "Turning solution-aware viewers onto this brand." },
  { id: "mechanism", name: "Mechanism", awarenessStage: "solution", structure: "Explain the unique mechanism that makes it work.", textSlots: ["headline", "body", "cta"], visualPattern: "A simple how-it-works diagram of the product's mechanism.", bestFor: "Differentiating on a proprietary or clever mechanism." },
  { id: "science", name: "Science", awarenessStage: "solution", structure: "Back the claim with study, data, or clinical framing.", textSlots: ["headline", "stat", "cta"], visualPattern: "Clean data-led visual with a study stat and the product.", bestFor: "Categories where evidence drives credibility." },
  { id: "results", name: "Results", awarenessStage: "solution", structure: "Show the measurable outcome the product produces.", textSlots: ["headline", "stat", "cta"], visualPattern: "A results readout (chart, number, or before/after metric) with the product.", bestFor: "Outcome-led products with quantifiable results." },
  { id: "lifestyle", name: "Lifestyle", awarenessStage: "unaware", structure: "Show the aspirational life the product fits into.", textSlots: ["headline", "cta"], visualPattern: "Product woven into an aspirational real-life scene.", bestFor: "Brand-building and desire at the top of the funnel." },
  { id: "identity", name: "Identity", awarenessStage: "unaware", structure: "Speak to who the buyer is, not just what they buy.", textSlots: ["headline", "cta"], visualPattern: "A person the target identifies with, product as part of their identity.", bestFor: "Identity-driven brands and tribes." },
  { id: "community", name: "Community", awarenessStage: "unaware", structure: "Show the community or movement around the brand.", textSlots: ["headline", "body", "cta"], visualPattern: "A group or community scene united by the brand.", bestFor: "Movement-led brands where belonging is the draw." },
  { id: "challenge", name: "Challenge", awarenessStage: "unaware", structure: "Invite the viewer into a challenge the product supports.", textSlots: ["headline", "body", "cta"], visualPattern: "A challenge framing (e.g. '30 days') with the product as the enabler.", bestFor: "Engagement-led campaigns and habit-forming products." },
  { id: "checklist", name: "Checklist", awarenessStage: "problem", structure: "A checklist of symptoms or needs the viewer ticks off.", textSlots: ["headline", "body", "cta"], visualPattern: "A ticked checklist of pains the product addresses.", bestFor: "Helping viewers self-diagnose into the problem." },
  { id: "stat", name: "Stat", awarenessStage: "unaware", structure: "One striking statistic carries the whole ad.", textSlots: ["stat", "headline", "cta"], visualPattern: "An oversized number as the hero with a short supporting line.", bestFor: "Stopping the scroll with a surprising figure." },
  { id: "data-point", name: "Data Point", awarenessStage: "unaware", structure: "A single data point reframes how the viewer sees the category.", textSlots: ["stat", "body", "cta"], visualPattern: "A clean data callout with light context and the product.", bestFor: "Analytical audiences persuaded by evidence." },
  { id: "mistake", name: "Mistake", awarenessStage: "problem", structure: "Call out a common mistake the viewer is likely making.", textSlots: ["headline", "body", "cta"], visualPattern: "The mistake shown as an error, corrected by the product's approach.", bestFor: "Pattern-interrupt for a habit the audience should drop." },
  { id: "warning", name: "Warning", awarenessStage: "problem", structure: "Warn about a risk or downside the viewer overlooks.", textSlots: ["headline", "body", "cta"], visualPattern: "A cautionary visual (warning motif) tied to the unsolved problem.", bestFor: "High-stakes categories where risk drives action." },
  { id: "contrarian", name: "Contrarian", awarenessStage: "unaware", structure: "Take a bold stance against the conventional wisdom.", textSlots: ["headline", "body", "cta"], visualPattern: "A provocative counter-claim on a bold, minimal background.", bestFor: "Cutting through with a strong, debate-starting angle." },
  { id: "curiosity", name: "Curiosity", awarenessStage: "unaware", structure: "Open a curiosity gap the viewer needs to close.", textSlots: ["headline", "cta"], visualPattern: "An intriguing partial reveal that withholds the payoff.", bestFor: "Maximising clicks with an unresolved hook." },
  { id: "question", name: "Question", awarenessStage: "unaware", structure: "Ask a direct question the target instantly answers 'yes' to.", textSlots: ["headline", "cta"], visualPattern: "A large question overlaid on a relatable scene.", bestFor: "Self-qualifying the right viewer at the top of funnel." },
  { id: "direct-response", name: "Direct Response", awarenessStage: "most_aware", structure: "A blunt, benefit-led pitch with a hard call to action.", textSlots: ["headline", "offer", "cta"], visualPattern: "Product, clear offer, and an unmissable CTA button.", bestFor: "Squeezing conversions from ready-to-buy traffic." },
  { id: "product-breakdown", name: "Product Breakdown", awarenessStage: "product", structure: "Deconstruct the product into its notable components.", textSlots: ["headline", "body", "cta"], visualPattern: "An exploded or annotated view of the product's parts.", bestFor: "Considered purchases where build detail matters." },
  { id: "ingredient-stack", name: "Ingredient Stack", awarenessStage: "product", structure: "Stack the key ingredients and what each contributes.", textSlots: ["headline", "body", "cta"], visualPattern: "A vertical stack of ingredients, each with a one-line role.", bestFor: "Formulation-led products with a strong ingredient list." },
  { id: "feature-stack", name: "Feature Stack", awarenessStage: "product", structure: "Stack the standout features in a scannable column.", textSlots: ["headline", "body", "cta"], visualPattern: "A stacked feature list with icons beside the product.", bestFor: "Feature-rich products that win on spec." },
  { id: "benefit-stack", name: "Benefit Stack", awarenessStage: "product", structure: "Stack the benefits (not features) in a scannable column.", textSlots: ["headline", "body", "cta"], visualPattern: "A stacked benefit list with icons beside the product.", bestFor: "Leading with outcomes over specifications." },
  { id: "transformation", name: "Transformation", awarenessStage: "solution", structure: "Show the arc from starting state to transformed state.", textSlots: ["headline", "body", "cta"], visualPattern: "A journey visual from problem-state to improved-state with the product.", bestFor: "Products defined by the change they create over time." },
  { id: "timeline", name: "Timeline", awarenessStage: "solution", structure: "Lay out results across a timeline (day 1, week 2, month 1).", textSlots: ["headline", "body", "cta"], visualPattern: "A horizontal timeline of milestones the product delivers.", bestFor: "Products with staged, time-based results." },
  { id: "step-by-step", name: "Step-by-Step", awarenessStage: "solution", structure: "Number the steps to the outcome, product embedded in each.", textSlots: ["headline", "body", "cta"], visualPattern: "Numbered step panels showing the simple process.", bestFor: "Showing how easy the product is to use." },
  { id: "how-it-works", name: "How It Works", awarenessStage: "solution", structure: "Walk through how the product works in three beats.", textSlots: ["headline", "body", "cta"], visualPattern: "A three-part how-it-works flow with simple icons.", bestFor: "Novel products that need a quick mental model." },
  { id: "what-nobody-tells-you", name: "What Nobody Tells You", awarenessStage: "unaware", structure: "Reveal an insider truth the category hides.", textSlots: ["headline", "body", "cta"], visualPattern: "A 'the truth about...' reveal on a bold background.", bestFor: "Insight-led hooks that build trust through candour." },
  { id: "stop-doing-this", name: "Stop Doing This", awarenessStage: "problem", structure: "Tell the viewer to stop a harmful habit.", textSlots: ["headline", "body", "cta"], visualPattern: "A crossed-out bad habit contrasted with the better way.", bestFor: "Pattern-interrupt around a common bad practice." },
  { id: "instead-do-this", name: "Instead Do This", awarenessStage: "solution", structure: "Replace the bad habit with the product-led better way.", textSlots: ["headline", "body", "cta"], visualPattern: "The recommended action shown positively with the product.", bestFor: "The constructive follow-up to a 'stop doing this' angle." },
  { id: "if-you-have-x", name: "If You Have X", awarenessStage: "problem", structure: "'If you have X problem, this is for you' targeting.", textSlots: ["headline", "body", "cta"], visualPattern: "The specific condition depicted, product offered as the answer.", bestFor: "Sharp targeting of a well-defined problem segment." },
  { id: "for-people-who", name: "For People Who", awarenessStage: "problem", structure: "'For people who...' calls out a precise audience.", textSlots: ["headline", "body", "cta"], visualPattern: "A relatable persona scene that self-selects the right viewer.", bestFor: "Qualifying a niche audience explicitly." },
  { id: "made-for", name: "Made For", awarenessStage: "product", structure: "State exactly who and what the product was made for.", textSlots: ["headline", "subhead", "cta"], visualPattern: "Product with its intended use-case and user clearly shown.", bestFor: "Purpose-built products with a clear ideal fit." },
  { id: "not-for", name: "Not For", awarenessStage: "product", structure: "State who the product is NOT for, to sharpen the fit.", textSlots: ["headline", "body", "cta"], visualPattern: "A confident 'not for everyone' framing with the product.", bestFor: "Premium or niche products that win by exclusion." },
  { id: "the-difference", name: "The Difference", awarenessStage: "product", structure: "Isolate the one thing that makes this different.", textSlots: ["headline", "body", "cta"], visualPattern: "A single differentiator spotlighted beside the product.", bestFor: "Cutting a crowded category down to one clear edge." },
  { id: "why-customers-switch", name: "Why Customers Switch", awarenessStage: "product", structure: "Explain why buyers leave the alternative for this.", textSlots: ["headline", "body", "cta"], visualPattern: "A switch-over visual from the old choice to the brand.", bestFor: "Winning share from an incumbent competitor." },
  { id: "why-we-built-this", name: "Why We Built This", awarenessStage: "solution", structure: "The origin story: the gap that made the product necessary.", textSlots: ["headline", "body", "cta"], visualPattern: "A narrative visual of the founding problem and the product's answer.", bestFor: "Mission-led brands earning trust through purpose." },
  { id: "what-makes-us-different", name: "What Makes Us Different", awarenessStage: "product", structure: "List the few things that set the brand apart.", textSlots: ["headline", "body", "cta"], visualPattern: "A short differentiators list beside a confident product hero.", bestFor: "Summarising the brand's edge in one frame." },
];

// Look up one concept format by id. Returns undefined for an unknown id (never throws, never invents).
export function getConceptFormat(id: string): ConceptFormat | undefined {
  return CONCEPT_FORMATS.find((c) => c.id === id);
}
