// Auto-generated from the product KPI catalog (162 KPIs). Names sanitized.
// `metaOnly` flags the KPIs computable from the Meta account alone today; the rest
// need Shopify / GA4 / finance / the creative decoder and show a gated state.

export type Kpi = {
  code: string; name: string; group: string; funnelStage: string;
  unit: string; formula: string; direction: string; tier: string;
  priority: string; source: string; platform: string; meaning: string; metaOnly: boolean;
};

export const KPI_CATALOG: Kpi[] = [
  {
    "code": "COGS",
    "name": "Cost of goods sold",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "Sum of unit cost x units sold",
    "direction": "Down = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Finance sheet (typed by a person)",
    "platform": "Finance sheet",
    "meaning": "What the product itself cost you, before any marketing.",
    "metaOnly": false
  },
  {
    "code": "NEWCUST",
    "name": "New customers",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "count",
    "formula": "Count where customer is first-time",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Shopify new vs returning flag",
    "platform": "Shopify / CRM",
    "meaning": "Count of first-time buyers, not repeat buyers.",
    "metaOnly": false
  },
  {
    "code": "REVENUE",
    "name": "Revenue (sales value)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "Sum of order value",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Shopify / GA4 purchase revenue",
    "platform": "Shopify / GA4 / CRM",
    "meaning": "Total money customers actually paid you.",
    "metaOnly": false
  },
  {
    "code": "SPEND",
    "name": "Amount spent",
    "group": "Cost",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "Sum of spend",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / Google / Bing / TikTok",
    "platform": "All ad platforms",
    "meaning": "Total money you paid the platform in the period.",
    "metaOnly": true
  },
  {
    "code": "CAC",
    "name": "Customer acquisition cost (blended)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "total marketing spend / new customers",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Blended spend + Shopify new customers",
    "platform": "All",
    "meaning": "Total marketing money divided by every new customer, across all channels.",
    "metaOnly": false
  },
  {
    "code": "MER",
    "name": "Marketing efficiency ratio (blended)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "total revenue / total ad spend",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Shopify revenue + blended spend",
    "platform": "All",
    "meaning": "Total sales divided by total ad spend. The whole-business ROAS.",
    "metaOnly": false
  },
  {
    "code": "NCAC",
    "name": "New-customer CAC (per platform)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "platform spend / platform new-customer conversions",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Platform spend + new-customer tagged conversions",
    "platform": "All",
    "meaning": "What one platform paid to bring one brand-new customer, not a repeat.",
    "metaOnly": false
  },
  {
    "code": "AMER",
    "name": "New-customer MER (aMER)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "new-customer revenue / total ad spend",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify new-customer revenue + spend",
    "platform": "All",
    "meaning": "Sales from new customers only, divided by total spend. Strips repeat buyers out.",
    "metaOnly": false
  },
  {
    "code": "CM",
    "name": "Contribution margin per order",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "%",
    "formula": "(revenue - COGS - shipping - fees - returns) / revenue x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify + finance sheet",
    "platform": "Finance + Shopify",
    "meaning": "What is left from a sale after product cost, shipping, returns and fees.",
    "metaOnly": false
  },
  {
    "code": "CONTRIB_ROAS",
    "name": "Contribution-margin ROAS",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "(revenue x margin percent) / ad spend",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "CM + spend",
    "platform": "All",
    "meaning": "ROAS measured on profit left after costs, not on top-line sales.",
    "metaOnly": false
  },
  {
    "code": "NET_MARGIN",
    "name": "Net profit margin",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "%",
    "formula": "(revenue - all costs - ad spend) / revenue x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Finance sheet",
    "platform": "Finance",
    "meaning": "Final profit as a share of sales, after everything including ad spend.",
    "metaOnly": false
  },
  {
    "code": "LTV",
    "name": "Lifetime value (customer)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "total revenue from a customer over their life",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P4",
    "source": "Shopify order history by customer",
    "platform": "Shopify / CRM",
    "meaning": "Total money one customer spends with you over their whole life.",
    "metaOnly": false
  },
  {
    "code": "LTV60",
    "name": "60-day LTV",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "Rs",
    "formula": "revenue per customer within 60 days of first order",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P4",
    "source": "Shopify cohort by first-order date",
    "platform": "Shopify",
    "meaning": "Money a customer spends in their first 60 days. A fast, fair early read.",
    "metaOnly": false
  },
  {
    "code": "LTV_CAC",
    "name": "LTV to CAC ratio",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "LTV / CAC",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P4",
    "source": "LTV + CAC",
    "platform": "All",
    "meaning": "How many rupees a customer returns for every rupee spent to get them.",
    "metaOnly": false
  },
  {
    "code": "PAYBACK",
    "name": "CAC payback period",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "months",
    "formula": "CAC / (monthly margin per customer)",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P4",
    "source": "CAC + monthly margin",
    "platform": "All",
    "meaning": "How many months until a customer pays back what it cost to get them.",
    "metaOnly": false
  },
  {
    "code": "MARGINAL_ROAS",
    "name": "Marginal ROAS (last rupee)",
    "group": "Business",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "change in revenue / change in spend at the current level",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P5",
    "source": "Spend-vs-revenue curve from history",
    "platform": "All",
    "meaning": "What the NEXT rupee of spend earns, not the average of all rupees.",
    "metaOnly": false
  },
  {
    "code": "SIGNAL_MER",
    "name": "Signal-adjusted MER",
    "group": "Measurement",
    "funnelStage": "F0 Economics",
    "unit": "ratio",
    "formula": "MER / (order coverage percent / 100)",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P5",
    "source": "MER + coverage from reconciliation",
    "platform": "All",
    "meaning": "MER corrected for how much tracking is actually being captured.",
    "metaOnly": false
  },
  {
    "code": "CLICKS",
    "name": "Clicks (all)",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "count",
    "formula": "Count of all clicks",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "Every click on the ad, including likes and expands, not just link clicks.",
    "metaOnly": true
  },
  {
    "code": "IMPR",
    "name": "Impressions",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "count",
    "formula": "Count of times shown",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / Google / Bing / TikTok",
    "platform": "All ad platforms",
    "meaning": "Number of times your ad appeared on a screen. Not people, appearances.",
    "metaOnly": true
  },
  {
    "code": "LINKCLICKS",
    "name": "Link clicks",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "count",
    "formula": "Count of link clicks",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Clicks that actually go to your website, not likes or shares.",
    "metaOnly": true
  },
  {
    "code": "OUTCLICKS",
    "name": "Outbound clicks",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "count",
    "formula": "Count of outbound clicks",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "Clicks that leave the platform for your site. Stricter than link clicks.",
    "metaOnly": true
  },
  {
    "code": "REACH",
    "name": "Reach (unique people)",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "count",
    "formula": "Count of unique people",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "How many different people saw the ad at least once.",
    "metaOnly": true
  },
  {
    "code": "CPC_ALL",
    "name": "CPC (all clicks)",
    "group": "Cost",
    "funnelStage": "F1 Delivery",
    "unit": "Rs",
    "formula": "spend / all clicks",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "Cost for any click, including non-link ones. Looks cheaper than it is.",
    "metaOnly": true
  },
  {
    "code": "CPC_LINK",
    "name": "CPC (link clicks)",
    "group": "Cost",
    "funnelStage": "F1 Delivery",
    "unit": "Rs",
    "formula": "spend / link clicks",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "Cost for one click to your website. The one that matters.",
    "metaOnly": true
  },
  {
    "code": "CPM",
    "name": "Cost per 1,000 impressions",
    "group": "Cost",
    "funnelStage": "F1 Delivery",
    "unit": "Rs",
    "formula": "spend / impressions x 1000",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "What it costs to show the ad one thousand times. Rent for attention.",
    "metaOnly": true
  },
  {
    "code": "CTR_ALL",
    "name": "CTR (all clicks)",
    "group": "Creative",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "all clicks / impressions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "Share of viewers who clicked anything on the ad.",
    "metaOnly": true
  },
  {
    "code": "CTR_LINK",
    "name": "CTR (link)",
    "group": "Creative",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "link clicks / impressions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "Share of viewers who clicked through to the site.",
    "metaOnly": true
  },
  {
    "code": "BUDGET_UTIL",
    "name": "Budget utilization",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "actual spend / planned budget x 100",
    "direction": "Target band",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Platform spend vs plan",
    "platform": "All ad platforms",
    "meaning": "How much of the planned budget actually got spent.",
    "metaOnly": false
  },
  {
    "code": "FREQ",
    "name": "Frequency",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "ratio",
    "formula": "impressions / reach",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Average times one person saw the ad.",
    "metaOnly": true
  },
  {
    "code": "OUT_CTR",
    "name": "Outbound CTR",
    "group": "Creative",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "outbound clicks / impressions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "Share who clicked out to your site. The strictest click rate.",
    "metaOnly": true
  },
  {
    "code": "FTI",
    "name": "First-time impression ratio",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "first-time impressions / total impressions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "Share of impressions going to people seeing the ad for the first time.",
    "metaOnly": true
  },
  {
    "code": "PACING",
    "name": "Budget pacing",
    "group": "Delivery",
    "funnelStage": "F1 Delivery",
    "unit": "%",
    "formula": "spend so far / expected spend by now x 100",
    "direction": "Target band",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Intraday platform spend",
    "platform": "All ad platforms",
    "meaning": "Whether spend is even through the day or dumped early.",
    "metaOnly": false
  },
  {
    "code": "THRUPLAY",
    "name": "ThruPlays",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "count",
    "formula": "Count of ThruPlays",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "People who watched to 15 seconds or to the end if shorter.",
    "metaOnly": true
  },
  {
    "code": "TRUEVIEW",
    "name": "TrueView views",
    "group": "Delivery",
    "funnelStage": "F2 Creative",
    "unit": "count",
    "formula": "Count of TrueView views",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Google Ads (renamed from Views in Oct 2025)",
    "platform": "Google YouTube",
    "meaning": "Counted watches on YouTube. A view is 30s or the end, or a click.",
    "metaOnly": false
  },
  {
    "code": "VID3S",
    "name": "3-second video views",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "count",
    "formula": "Count of 3s views",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Count of people who watched at least 3 seconds.",
    "metaOnly": true
  },
  {
    "code": "CPV",
    "name": "Cost per view",
    "group": "Cost",
    "funnelStage": "F2 Creative",
    "unit": "Rs",
    "formula": "spend / TrueView views",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Google Ads",
    "platform": "Google YouTube",
    "meaning": "What you pay for one counted YouTube view.",
    "metaOnly": false
  },
  {
    "code": "VIEWRATE",
    "name": "TrueView view rate (VTR)",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "TrueView views / impressions x 100",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "Google Ads",
    "platform": "Google YouTube",
    "meaning": "Share of impressions that became a counted view.",
    "metaOnly": false
  },
  {
    "code": "CP_3S",
    "name": "Cost per 3-second view",
    "group": "Cost",
    "funnelStage": "F2 Creative",
    "unit": "Rs",
    "formula": "spend / 3s views",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "What you pay for one 3-second watch.",
    "metaOnly": true
  },
  {
    "code": "CP_THRU",
    "name": "Cost per ThruPlay",
    "group": "Cost",
    "funnelStage": "F2 Creative",
    "unit": "Rs",
    "formula": "spend / ThruPlays",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "What you pay for one 15-second-or-complete watch.",
    "metaOnly": true
  },
  {
    "code": "ENGAGE_RATE",
    "name": "Engagement rate (social)",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "engagements / reach x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Share of people who reacted, saved, shared or commented.",
    "metaOnly": true
  },
  {
    "code": "HOLD",
    "name": "Hold rate",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "ThruPlays / 3s views x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "Of those who stopped, how many stayed to 15 seconds. The story test.",
    "metaOnly": true
  },
  {
    "code": "HOOK",
    "name": "Hook rate (thumbstop)",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "3s views / impressions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Share of viewers who stopped scrolling for 3 seconds. The opening test.",
    "metaOnly": true
  },
  {
    "code": "VID100",
    "name": "Video played to 100 percent",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "100% views / video plays x 100",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Meta / Google YouTube",
    "platform": "Meta / Google",
    "meaning": "Share who watched the whole video.",
    "metaOnly": true
  },
  {
    "code": "VID25",
    "name": "Video played to 25 percent",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "25% views / video plays x 100",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Meta / Google YouTube",
    "platform": "Meta / Google",
    "meaning": "Share of viewers who reached a quarter of the video.",
    "metaOnly": true
  },
  {
    "code": "VID50",
    "name": "Video played to 50 percent",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "50% views / video plays x 100",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Meta / Google YouTube",
    "platform": "Meta / Google",
    "meaning": "Share who reached the halfway point.",
    "metaOnly": true
  },
  {
    "code": "VID75",
    "name": "Video played to 75 percent",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "%",
    "formula": "75% views / video plays x 100",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Meta / Google YouTube",
    "platform": "Meta / Google",
    "meaning": "Share who reached three quarters.",
    "metaOnly": true
  },
  {
    "code": "VID_AVGTIME",
    "name": "Average video play time",
    "group": "Creative",
    "funnelStage": "F2 Creative",
    "unit": "sec",
    "formula": "total watch time / plays",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / TikTok",
    "platform": "Meta / TikTok",
    "meaning": "Average seconds people spent watching the video.",
    "metaOnly": true
  },
  {
    "code": "EVC",
    "name": "Engaged-view conversions",
    "group": "Measurement",
    "funnelStage": "F2 Creative",
    "unit": "count",
    "formula": "Count of engaged-view conversions",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P3",
    "source": "Google Ads",
    "platform": "Google YouTube",
    "meaning": "Sales from people who watched 10+ seconds, did not click, then bought.",
    "metaOnly": false
  },
  {
    "code": "LPV",
    "name": "Landing page views",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "count",
    "formula": "Count of landing page views",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "People who clicked and the page actually loaded. Fewer than link clicks.",
    "metaOnly": false
  },
  {
    "code": "NEWUSERS",
    "name": "New users",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "count",
    "formula": "Count of new users",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "People visiting the site for the first time.",
    "metaOnly": false
  },
  {
    "code": "SESSIONS",
    "name": "Sessions",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "count",
    "formula": "Count of sessions",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Visits to your site, counted by GA4.",
    "metaOnly": false
  },
  {
    "code": "USERS",
    "name": "Active users",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "count",
    "formula": "Count of active users",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Distinct people who visited, not visits.",
    "metaOnly": false
  },
  {
    "code": "AVG_ENG_TIME",
    "name": "Avg engagement time per session",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "sec",
    "formula": "total engagement time / sessions",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Average active seconds a visitor spent per visit.",
    "metaOnly": false
  },
  {
    "code": "ENG_RATE_SITE",
    "name": "Engagement rate (site)",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "%",
    "formula": "engaged sessions / sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits that were engaged, not instant leaves.",
    "metaOnly": false
  },
  {
    "code": "ENG_SESS",
    "name": "Engaged sessions",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "count",
    "formula": "Count of engaged sessions",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Visits over 10 seconds, or with a key event, or 2+ pages.",
    "metaOnly": false
  },
  {
    "code": "LP_SPEED",
    "name": "Landing page load speed",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "sec",
    "formula": "Largest Contentful Paint in seconds",
    "direction": "Down = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "PageSpeed / Core Web Vitals",
    "platform": "GA4 / PageSpeed",
    "meaning": "How many seconds the page takes to become usable.",
    "metaOnly": false
  },
  {
    "code": "BOUNCE",
    "name": "Bounce rate (GA4)",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "%",
    "formula": "100 - engagement rate",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits that were NOT engaged. GA4 flipped this definition.",
    "metaOnly": false
  },
  {
    "code": "LPV_RATE",
    "name": "Click to landing rate",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "%",
    "formula": "landing page views / link clicks x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "Share of link clicks whose page actually loaded. Catches slow or broken pages.",
    "metaOnly": true
  },
  {
    "code": "PAGES_SESS",
    "name": "Pages per session",
    "group": "Funnel",
    "funnelStage": "F3 Landing",
    "unit": "ratio",
    "formula": "page views / sessions",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Average pages a visitor looked at.",
    "metaOnly": false
  },
  {
    "code": "RPS",
    "name": "Revenue per session (RPV)",
    "group": "Business",
    "funnelStage": "F3 Landing",
    "unit": "Rs",
    "formula": "revenue / sessions",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify + GA4",
    "platform": "GA4 / Shopify",
    "meaning": "Average money each visit is worth. Ties traffic quality to money.",
    "metaOnly": false
  },
  {
    "code": "ATC",
    "name": "Add to cart (count)",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "count",
    "formula": "Count of add to cart events",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta pixel / GA4 add_to_cart",
    "platform": "Meta / GA4 / Shopify",
    "meaning": "Count of times a product was put in the cart.",
    "metaOnly": false
  },
  {
    "code": "ITEMS_ATC",
    "name": "Items added to cart (GA4)",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "count",
    "formula": "Sum of items in add_to_cart",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "GA4 item-scoped",
    "platform": "GA4",
    "meaning": "Count of individual items added, not cart events.",
    "metaOnly": false
  },
  {
    "code": "VIEWCONTENT",
    "name": "View content (PDP views)",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "count",
    "formula": "Count of product page views",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta pixel / GA4 view_item",
    "platform": "Meta / GA4",
    "meaning": "People who looked at a product page.",
    "metaOnly": false
  },
  {
    "code": "ATC_RATE",
    "name": "Add-to-cart rate",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "%",
    "formula": "add to carts / sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4 / Shopify",
    "platform": "GA4 / Shopify",
    "meaning": "Share of visits that added something to cart.",
    "metaOnly": false
  },
  {
    "code": "CP_ATC",
    "name": "Cost per add to cart",
    "group": "Cost",
    "funnelStage": "F4 Cart",
    "unit": "Rs",
    "formula": "spend / add to carts",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "What you pay for one add to cart.",
    "metaOnly": true
  },
  {
    "code": "ATC_LPV",
    "name": "ATC to landing rate",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "%",
    "formula": "add to carts / landing page views x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who landed, how many added to cart. Judges the page and offer.",
    "metaOnly": false
  },
  {
    "code": "ATC_VC",
    "name": "ATC to product-view rate",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "%",
    "formula": "add to carts / view content x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who viewed a product, how many added it. Judges the product page.",
    "metaOnly": false
  },
  {
    "code": "CART_ABANDON",
    "name": "Cart abandonment rate",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "%",
    "formula": "(1 - purchases / add to carts) x 100",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify / GA4",
    "platform": "Shopify / GA4",
    "meaning": "Share of carts that never became an order.",
    "metaOnly": false
  },
  {
    "code": "VC_RATE",
    "name": "View content rate",
    "group": "Funnel",
    "funnelStage": "F4 Cart",
    "unit": "%",
    "formula": "view content / landing page views x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Share of arrivals who looked at a product.",
    "metaOnly": false
  },
  {
    "code": "ADD_PAYMENT",
    "name": "Add payment info (count)",
    "group": "Funnel",
    "funnelStage": "F5 Checkout",
    "unit": "count",
    "formula": "Count of add_payment_info events",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta pixel / GA4 add_payment_info",
    "platform": "Meta / GA4",
    "meaning": "Count of people who entered payment details. Very close to buying.",
    "metaOnly": false
  },
  {
    "code": "IC",
    "name": "Initiate checkout (count)",
    "group": "Funnel",
    "funnelStage": "F5 Checkout",
    "unit": "count",
    "formula": "Count of begin checkout events",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta pixel / GA4 begin_checkout",
    "platform": "Meta / GA4 / Shopify",
    "meaning": "Count of times someone started the checkout.",
    "metaOnly": false
  },
  {
    "code": "CP_IC",
    "name": "Cost per initiate checkout",
    "group": "Cost",
    "funnelStage": "F5 Checkout",
    "unit": "Rs",
    "formula": "spend / begin checkouts",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "What you pay for one started checkout.",
    "metaOnly": true
  },
  {
    "code": "IC_RATE",
    "name": "Initiate checkout rate",
    "group": "Funnel",
    "funnelStage": "F5 Checkout",
    "unit": "%",
    "formula": "begin checkout / sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4 / Shopify",
    "platform": "GA4 / Shopify",
    "meaning": "Share of visits that started checkout.",
    "metaOnly": false
  },
  {
    "code": "CHECKOUT_COMPLETE",
    "name": "Checkout completion rate",
    "group": "Funnel",
    "funnelStage": "F5 Checkout",
    "unit": "%",
    "formula": "purchases / begin checkouts x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify / GA4",
    "platform": "Shopify / GA4",
    "meaning": "Of people who started checkout, how many finished the order.",
    "metaOnly": false
  },
  {
    "code": "IC_ATC",
    "name": "Checkout to cart rate (IC/ATC)",
    "group": "Funnel",
    "funnelStage": "F5 Checkout",
    "unit": "%",
    "formula": "begin checkout / add to carts x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who added to cart, how many started checkout. A key leak point.",
    "metaOnly": false
  },
  {
    "code": "CONV_VALUE",
    "name": "Conversion value",
    "group": "Business",
    "funnelStage": "F6 Purchase",
    "unit": "Rs",
    "formula": "Sum of conversion value",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / Google / Bing",
    "platform": "All ad platforms",
    "meaning": "Sale value the platform credits to its ads.",
    "metaOnly": true
  },
  {
    "code": "ORDERS",
    "name": "Orders (Shopify)",
    "group": "Business",
    "funnelStage": "F6 Purchase",
    "unit": "count",
    "formula": "Count of orders",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Real orders placed on the store, the source of truth.",
    "metaOnly": false
  },
  {
    "code": "PURCHASES",
    "name": "Purchases (conversions)",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "count",
    "formula": "Count of purchase events",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Meta / Google / Shopify / GA4",
    "platform": "All / Shopify",
    "meaning": "Count of completed orders or conversions.",
    "metaOnly": false
  },
  {
    "code": "AOV",
    "name": "Average order value",
    "group": "Business",
    "funnelStage": "F6 Purchase",
    "unit": "Rs",
    "formula": "revenue / orders",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Average money per order.",
    "metaOnly": false
  },
  {
    "code": "CPA",
    "name": "Cost per acquisition",
    "group": "Efficiency",
    "funnelStage": "F6 Purchase",
    "unit": "Rs",
    "formula": "spend / conversions",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "What you pay for one conversion, order or lead.",
    "metaOnly": true
  },
  {
    "code": "CPP",
    "name": "Cost per purchase",
    "group": "Efficiency",
    "funnelStage": "F6 Purchase",
    "unit": "Rs",
    "formula": "spend / purchases",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta",
    "platform": "Meta",
    "meaning": "What you pay the platform for one order.",
    "metaOnly": true
  },
  {
    "code": "CVR",
    "name": "Conversion rate (site)",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "%",
    "formula": "purchases / sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4 / Shopify",
    "platform": "GA4 / Shopify",
    "meaning": "Share of visits that became an order.",
    "metaOnly": false
  },
  {
    "code": "CVR_CLICK",
    "name": "Conversion rate (per click)",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "%",
    "formula": "purchases / link clicks x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "Share of ad clicks that became an order.",
    "metaOnly": true
  },
  {
    "code": "ROAS",
    "name": "Return on ad spend (platform)",
    "group": "Business",
    "funnelStage": "F6 Purchase",
    "unit": "ratio",
    "formula": "conversion value / spend",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "Sale value the platform claims per rupee of spend.",
    "metaOnly": true
  },
  {
    "code": "PUR_ATC",
    "name": "Purchase to cart rate (Purchase/ATC)",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "%",
    "formula": "purchases / add to carts x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who added to cart, how many bought.",
    "metaOnly": false
  },
  {
    "code": "PUR_IC",
    "name": "Purchase to checkout rate (Purchase/IC)",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "%",
    "formula": "purchases / begin checkouts x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who started checkout, how many finished. Same as completion.",
    "metaOnly": false
  },
  {
    "code": "PUR_LPV",
    "name": "Purchase to landing rate",
    "group": "Funnel",
    "funnelStage": "F6 Purchase",
    "unit": "%",
    "formula": "purchases / landing page views x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta / GA4",
    "platform": "Meta / GA4",
    "meaning": "Of people who landed, how many bought. Whole-page conversion.",
    "metaOnly": false
  },
  {
    "code": "UPT",
    "name": "Units per transaction",
    "group": "Business",
    "funnelStage": "F6 Purchase",
    "unit": "ratio",
    "formula": "units sold / orders",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Average number of items in an order.",
    "metaOnly": false
  },
  {
    "code": "NEW_RET_MIX",
    "name": "New vs returning mix",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "new-customer orders / total orders x 100",
    "direction": "Target band",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Split of sales between first-time and repeat buyers.",
    "metaOnly": false
  },
  {
    "code": "RETURN_RATE",
    "name": "Return / refund rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "returned or refunded orders / total orders x 100",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Share of orders sent back or refunded.",
    "metaOnly": false
  },
  {
    "code": "RET_RATE",
    "name": "Returning customer rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "returning customers / total customers x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Share of customers who came back to buy again.",
    "metaOnly": false
  },
  {
    "code": "CHURN",
    "name": "Customer churn rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "lost customers / customers at start x 100",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify / CRM",
    "platform": "Shopify / CRM",
    "meaning": "Share of customers who stopped buying in a period.",
    "metaOnly": false
  },
  {
    "code": "REPEAT_RATE",
    "name": "Repeat purchase rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "customers with 2+ orders / total customers x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Share of customers with more than one order.",
    "metaOnly": false
  },
  {
    "code": "SUB_RATE",
    "name": "Subscription rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "subscription orders / total orders x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Share of orders on a repeating subscription.",
    "metaOnly": false
  },
  {
    "code": "NPS",
    "name": "Net promoter score",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "score",
    "formula": "percent promoters - percent detractors",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P3",
    "source": "Post-purchase survey",
    "platform": "Survey",
    "meaning": "How likely customers are to recommend you, minus the unhappy ones.",
    "metaOnly": false
  },
  {
    "code": "RET30",
    "name": "30-day repeat rate",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "%",
    "formula": "repeat within 30 days / new customers x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Shopify cohort",
    "platform": "Shopify",
    "meaning": "Share of new customers who bought again within 30 days.",
    "metaOnly": false
  },
  {
    "code": "TIME_BETWEEN",
    "name": "Time between orders",
    "group": "Business",
    "funnelStage": "F7 Retention",
    "unit": "days",
    "formula": "average days between a customer's orders",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Shopify",
    "platform": "Shopify",
    "meaning": "Average days a customer waits before buying again.",
    "metaOnly": false
  },
  {
    "code": "CTC",
    "name": "Click-through conversions",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "count",
    "formula": "Count of click-through conversions",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "Any ad platform",
    "platform": "All ad platforms",
    "meaning": "Sales from people who clicked the ad then bought.",
    "metaOnly": true
  },
  {
    "code": "EMQ",
    "name": "Event match quality",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "score",
    "formula": "Platform-scored 0 to 10",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Meta / Google Enhanced Conversions",
    "platform": "Meta / Google",
    "meaning": "How well your sale events are matched to real people. 0 to 10.",
    "metaOnly": true
  },
  {
    "code": "ORDER_COVERAGE",
    "name": "Order coverage rate",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "%",
    "formula": "platform purchases / shopify orders x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Meta + Shopify",
    "platform": "Meta vs Shopify",
    "meaning": "Share of real Shopify orders that the platform actually reported.",
    "metaOnly": false
  },
  {
    "code": "PPS",
    "name": "Post-purchase survey share",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "%",
    "formula": "responses naming a channel / total responses x 100",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P3",
    "source": "Post-purchase survey (Fairing etc)",
    "platform": "Survey",
    "meaning": "Where customers say they actually heard of you, in their words.",
    "metaOnly": false
  },
  {
    "code": "VTC",
    "name": "View-through conversions",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "count",
    "formula": "Count of view-through conversions",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P3",
    "source": "Meta / Google",
    "platform": "Meta / Google",
    "meaning": "Sales from people who saw but did not click, then bought.",
    "metaOnly": true
  },
  {
    "code": "PIXEL_CVD",
    "name": "Attribution gap (pixel minus platform)",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "Rs",
    "formula": "pixel conversion value - platform conversion value",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P4",
    "source": "Triple Whale",
    "platform": "Triple Whale",
    "meaning": "Difference between first-party tracked sales and what the platform claims.",
    "metaOnly": false
  },
  {
    "code": "INCREMENTALITY",
    "name": "Incremental lift (holdout)",
    "group": "Measurement",
    "funnelStage": "F8 Attribution",
    "unit": "%",
    "formula": "(treated sales - control sales) / control sales x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P5",
    "source": "Geo holdout or platform lift test",
    "platform": "Geo / lift test",
    "meaning": "Extra sales the ads truly caused, proven by holding out some areas.",
    "metaOnly": false
  },
  {
    "code": "SESS_CHANNEL",
    "name": "Sessions by channel",
    "group": "Funnel",
    "funnelStage": "GA4 Channels",
    "unit": "count",
    "formula": "Sessions grouped by session default channel group",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P0",
    "source": "GA4 session default channel group",
    "platform": "GA4",
    "meaning": "Visits split by where they came from: direct, organic, paid, and so on.",
    "metaOnly": false
  },
  {
    "code": "REV_CHANNEL",
    "name": "Revenue by channel",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "Rs",
    "formula": "Purchase revenue grouped by channel",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Sales split by the channel that brought the visit.",
    "metaOnly": false
  },
  {
    "code": "BRANDED_SHARE",
    "name": "Branded vs non-branded search",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "branded clicks / total search clicks x 100",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Google Ads / Search Console",
    "platform": "Google / GA4",
    "meaning": "Split of search clicks between your name and generic terms.",
    "metaOnly": false
  },
  {
    "code": "CVR_CHANNEL",
    "name": "Conversion rate by channel",
    "group": "Funnel",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "purchases by channel / sessions by channel x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Site conversion rate split by traffic source.",
    "metaOnly": false
  },
  {
    "code": "FIRST_CHANNEL",
    "name": "First-touch channel mix",
    "group": "Measurement",
    "funnelStage": "GA4 Channels",
    "unit": "count",
    "formula": "Customers grouped by first user default channel group",
    "direction": "Context",
    "tier": "Direct",
    "priority": "P2",
    "source": "GA4 first user channel",
    "platform": "GA4",
    "meaning": "Which channel first brought each customer, before they converted.",
    "metaOnly": false
  },
  {
    "code": "SHARE_DIRECT",
    "name": "Direct traffic share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "direct sessions / total sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from people typing your name or using a bookmark. Brand strength.",
    "metaOnly": false
  },
  {
    "code": "SHARE_EMAIL",
    "name": "Email and SMS share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "email sessions / total sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from email and SMS. Owned, near-free traffic.",
    "metaOnly": false
  },
  {
    "code": "SHARE_ORGANIC",
    "name": "Organic search share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "organic search sessions / total sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from unpaid Google search.",
    "metaOnly": false
  },
  {
    "code": "SHARE_PAIDSEARCH",
    "name": "Paid search share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "paid search sessions / total sessions x 100",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from paid Google and Bing search.",
    "metaOnly": false
  },
  {
    "code": "SHARE_PAIDSOCIAL",
    "name": "Paid social share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "paid social sessions / total sessions x 100",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P2",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from paid Meta, TikTok and similar.",
    "metaOnly": false
  },
  {
    "code": "AOV_CHANNEL",
    "name": "AOV by channel",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "Rs",
    "formula": "revenue by channel / orders by channel",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "GA4 / Shopify",
    "platform": "GA4 / Shopify",
    "meaning": "Average order value split by traffic source.",
    "metaOnly": false
  },
  {
    "code": "SHARE_AI",
    "name": "AI assistant share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "AI assistant sessions / total sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "GA4 (AI Assistants channel added 2026)",
    "platform": "GA4",
    "meaning": "Share of visits referred by ChatGPT, Gemini and similar. New in 2026.",
    "metaOnly": false
  },
  {
    "code": "SHARE_REFERRAL",
    "name": "Referral share",
    "group": "Business",
    "funnelStage": "GA4 Channels",
    "unit": "%",
    "formula": "referral sessions / total sessions x 100",
    "direction": "Context",
    "tier": "Calculated",
    "priority": "P3",
    "source": "GA4",
    "platform": "GA4",
    "meaning": "Share of visits from links on other websites.",
    "metaOnly": false
  },
  {
    "code": "TW_BLENDED_ROAS",
    "name": "Blended ROAS (Triple Whale)",
    "group": "Business",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "order revenue / blended ad spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "Triple Whale",
    "platform": "Triple Whale",
    "meaning": "All sales divided by all ad spend, across every channel together.",
    "metaOnly": false
  },
  {
    "code": "TW_MER",
    "name": "MER (Triple Whale)",
    "group": "Measurement",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "total revenue / blended ad spend",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Triple Whale",
    "platform": "Triple Whale",
    "meaning": "Whole-business efficiency, all spend against all sales, in one place.",
    "metaOnly": false
  },
  {
    "code": "NB_1DAY_ROAS",
    "name": "1-day ROAS (Northbeam)",
    "group": "Measurement",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "1-day attributed revenue / spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Northbeam",
    "platform": "Northbeam",
    "meaning": "Sales within one day of the click. Fast signal for daily decisions.",
    "metaOnly": false
  },
  {
    "code": "TW_NCPA",
    "name": "New-customer CPA (Triple Whale NCPA)",
    "group": "Business",
    "funnelStage": "3rd-party",
    "unit": "Rs",
    "formula": "blended ad spend / new-customer orders",
    "direction": "Down = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Triple Whale",
    "platform": "Triple Whale",
    "meaning": "Blended cost to get one brand-new customer.",
    "metaOnly": false
  },
  {
    "code": "TW_NCROAS",
    "name": "New-customer ROAS (Triple Whale)",
    "group": "Business",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "new-customer revenue / blended ad spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Triple Whale",
    "platform": "Triple Whale",
    "meaning": "New-customer sales divided by all spend.",
    "metaOnly": false
  },
  {
    "code": "TW_PIXEL_ROAS",
    "name": "Pixel ROAS (Triple Whale)",
    "group": "Measurement",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "pixel conversion value / spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Triple Whale pixel",
    "platform": "Triple Whale",
    "meaning": "Sales credited by Triple Whale's own first-party tracking, per channel.",
    "metaOnly": false
  },
  {
    "code": "NB_ROAS_MODEL",
    "name": "Attributed ROAS by model (Northbeam)",
    "group": "Measurement",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "attributed revenue / spend under the selected model",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P3",
    "source": "Northbeam",
    "platform": "Northbeam",
    "meaning": "ROAS under a chosen attribution model: first click, last click, linear, or clicks plus views.",
    "metaOnly": false
  },
  {
    "code": "WR_MULTITOUCH_ROI",
    "name": "Multi-touch ROI (Wicked Reports)",
    "group": "Measurement",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "attributed revenue across all touches / spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P3",
    "source": "Wicked Reports",
    "platform": "Wicked Reports",
    "meaning": "Return with credit shared across every touch in the journey, including email and SMS.",
    "metaOnly": false
  },
  {
    "code": "NB_LTV_ROAS",
    "name": "LTV ROAS (Northbeam)",
    "group": "Business",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "cohort lifetime revenue / spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P4",
    "source": "Northbeam",
    "platform": "Northbeam",
    "meaning": "Long-run ROAS counting the full value a cohort brings over time.",
    "metaOnly": false
  },
  {
    "code": "WR_COHORT_ROAS",
    "name": "Cohort ROAS (Wicked Reports)",
    "group": "Business",
    "funnelStage": "3rd-party",
    "unit": "ratio",
    "formula": "cohort lifetime revenue / campaign spend",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P4",
    "source": "Wicked Reports",
    "platform": "Wicked Reports",
    "meaning": "Lifetime revenue of each campaign's customers, including repeat and subscription.",
    "metaOnly": false
  },
  {
    "code": "LEADS",
    "name": "Leads",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "count",
    "formula": "Count of leads",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Ad platforms / forms / CRM",
    "platform": "Meta / Google / CRM",
    "meaning": "Count of people who gave their details.",
    "metaOnly": false
  },
  {
    "code": "CPL",
    "name": "Cost per lead",
    "group": "Cost",
    "funnelStage": "B2B Lead",
    "unit": "Rs",
    "formula": "spend / leads",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Ad platforms",
    "platform": "Meta / Google",
    "meaning": "What you pay for one lead.",
    "metaOnly": true
  },
  {
    "code": "CP_DEAL",
    "name": "Cost per closed deal",
    "group": "Cost",
    "funnelStage": "B2B Lead",
    "unit": "Rs",
    "formula": "spend / closed-won deals",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "CRM + ad spend",
    "platform": "CRM + spend",
    "meaning": "What marketing spent to win one paying customer.",
    "metaOnly": false
  },
  {
    "code": "LEAD_RATE",
    "name": "Lead rate (form fill rate)",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "leads / sessions x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "GA4 / CRM",
    "platform": "GA4 / CRM",
    "meaning": "Share of visits that became a lead.",
    "metaOnly": false
  },
  {
    "code": "MQL",
    "name": "Marketing qualified leads",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "count",
    "formula": "Count of MQLs",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "CRM / marketing automation",
    "platform": "CRM",
    "meaning": "Leads good enough for sales to look at.",
    "metaOnly": false
  },
  {
    "code": "PIPELINE",
    "name": "Pipeline value",
    "group": "Business",
    "funnelStage": "B2B Lead",
    "unit": "Rs",
    "formula": "sum of open deal values",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Total value of open deals sales are working on.",
    "metaOnly": false
  },
  {
    "code": "SQL",
    "name": "Sales qualified leads",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "count",
    "formula": "Count of SQLs",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Leads sales accepted as real opportunities.",
    "metaOnly": false
  },
  {
    "code": "CPQL",
    "name": "Cost per qualified lead",
    "group": "Cost",
    "funnelStage": "B2B Lead",
    "unit": "Rs",
    "formula": "spend / SQLs",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM + ad spend",
    "platform": "CRM + spend",
    "meaning": "What you pay for one sales-accepted lead.",
    "metaOnly": false
  },
  {
    "code": "CP_MQL",
    "name": "Cost per MQL",
    "group": "Cost",
    "funnelStage": "B2B Lead",
    "unit": "Rs",
    "formula": "spend / MQLs",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM + ad spend",
    "platform": "CRM + spend",
    "meaning": "What you pay for one qualified lead.",
    "metaOnly": false
  },
  {
    "code": "DEMO_BOOK",
    "name": "Demo booked rate",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "demos booked / leads x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM / scheduler",
    "platform": "CRM / Calendly",
    "meaning": "Share of leads who booked a demo or call.",
    "metaOnly": false
  },
  {
    "code": "DEMO_SHOW",
    "name": "Demo show-up rate",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "demos attended / demos booked x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM / scheduler",
    "platform": "CRM / Calendly",
    "meaning": "Share of booked demos where the person actually turned up.",
    "metaOnly": false
  },
  {
    "code": "MQL_RATE",
    "name": "Lead to MQL rate",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "MQLs / leads x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Share of leads that were good enough to qualify.",
    "metaOnly": false
  },
  {
    "code": "SQL_RATE",
    "name": "MQL to SQL rate",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "SQLs / MQLs x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Share of qualified leads sales accepted.",
    "metaOnly": false
  },
  {
    "code": "WIN_RATE",
    "name": "Win rate (SQL to closed)",
    "group": "Funnel",
    "funnelStage": "B2B Lead",
    "unit": "%",
    "formula": "closed-won deals / SQLs x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Share of opportunities that became paying customers.",
    "metaOnly": false
  },
  {
    "code": "PIPE_COVER",
    "name": "Pipeline coverage ratio",
    "group": "Business",
    "funnelStage": "B2B Lead",
    "unit": "ratio",
    "formula": "open pipeline value / revenue target",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Open pipeline compared to the target. Are there enough deals to hit goal.",
    "metaOnly": false
  },
  {
    "code": "SALES_CYCLE",
    "name": "Sales cycle length",
    "group": "Business",
    "funnelStage": "B2B Lead",
    "unit": "days",
    "formula": "average days from lead to close",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Average days from first touch to closed deal.",
    "metaOnly": false
  },
  {
    "code": "MRR",
    "name": "Monthly recurring revenue",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "sum of monthly subscription value",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Stripe / billing",
    "platform": "Billing",
    "meaning": "Predictable subscription revenue collected each month.",
    "metaOnly": false
  },
  {
    "code": "ACV",
    "name": "Average contract value",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "total contract value / number of contracts",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Average yearly value of one signed contract.",
    "metaOnly": false
  },
  {
    "code": "ARR",
    "name": "Annual recurring revenue",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "MRR x 12",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Yearly run-rate of subscription revenue.",
    "metaOnly": false
  },
  {
    "code": "NEW_MRR",
    "name": "New MRR",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "sum of new-customer monthly value",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P1",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Fresh subscription revenue added this month from new customers.",
    "metaOnly": false
  },
  {
    "code": "ACTIVATION",
    "name": "Activation rate",
    "group": "Funnel",
    "funnelStage": "SaaS Economics",
    "unit": "%",
    "formula": "activated users / signups x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Product analytics",
    "platform": "Product",
    "meaning": "Share of signups who reached the first real value moment.",
    "metaOnly": false
  },
  {
    "code": "ARPA",
    "name": "Average revenue per account",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "MRR / active accounts",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Average monthly revenue from one customer.",
    "metaOnly": false
  },
  {
    "code": "CHURN_MRR",
    "name": "Churned MRR",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "sum of lost monthly value",
    "direction": "Down = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Revenue lost this month from cancellations and downgrades.",
    "metaOnly": false
  },
  {
    "code": "EXPANSION_MRR",
    "name": "Expansion MRR",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "Rs",
    "formula": "sum of upgrade value this month",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P2",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Extra revenue from existing customers upgrading.",
    "metaOnly": false
  },
  {
    "code": "TRIAL_PAID",
    "name": "Trial to paid rate",
    "group": "Funnel",
    "funnelStage": "SaaS Economics",
    "unit": "%",
    "formula": "paid conversions / trials started x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P2",
    "source": "Billing / product",
    "platform": "Billing",
    "meaning": "Share of free trials that became paying customers.",
    "metaOnly": false
  },
  {
    "code": "GRR",
    "name": "Gross revenue retention",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "%",
    "formula": "(start MRR - churn - downgrades) / start MRR x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Revenue kept before any upgrades. Pure leak measure.",
    "metaOnly": false
  },
  {
    "code": "LOGO_CHURN",
    "name": "Logo churn rate",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "%",
    "formula": "lost customers / customers at start x 100",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Billing / CRM",
    "platform": "Billing",
    "meaning": "Share of customers who cancelled, counting accounts not money.",
    "metaOnly": false
  },
  {
    "code": "NRR",
    "name": "Net revenue retention",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "%",
    "formula": "(start MRR + expansion - churn) / start MRR x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P3",
    "source": "Billing",
    "platform": "Billing",
    "meaning": "Revenue kept from existing customers including upgrades, minus churn.",
    "metaOnly": false
  },
  {
    "code": "MAGIC",
    "name": "Magic number",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "ratio",
    "formula": "(new ARR in a quarter) / (prior quarter sales and marketing spend)",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P4",
    "source": "Billing + spend",
    "platform": "Billing",
    "meaning": "New yearly recurring revenue earned per rupee of sales and marketing.",
    "metaOnly": false
  },
  {
    "code": "RULE40",
    "name": "Rule of 40",
    "group": "Business",
    "funnelStage": "SaaS Economics",
    "unit": "score",
    "formula": "growth rate percent + profit margin percent",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P5",
    "source": "Billing + finance",
    "platform": "Billing",
    "meaning": "Growth rate plus profit margin. A quick whole-company health check.",
    "metaOnly": false
  },
  {
    "code": "BOOKED_CALLS",
    "name": "Booked calls",
    "group": "Funnel",
    "funnelStage": "Service",
    "unit": "count",
    "formula": "Count of booked calls",
    "direction": "Up = good",
    "tier": "Direct",
    "priority": "P0",
    "source": "Scheduler / CRM",
    "platform": "Calendly / CRM",
    "meaning": "Count of sales calls booked.",
    "metaOnly": false
  },
  {
    "code": "AVG_DEAL",
    "name": "Average deal size",
    "group": "Business",
    "funnelStage": "Service",
    "unit": "Rs",
    "formula": "total closed value / deals closed",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Average value of one closed client.",
    "metaOnly": false
  },
  {
    "code": "CLOSE_RATE",
    "name": "Close rate",
    "group": "Funnel",
    "funnelStage": "Service",
    "unit": "%",
    "formula": "deals closed / calls attended x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "CRM",
    "platform": "CRM",
    "meaning": "Share of sales calls that became paying clients.",
    "metaOnly": false
  },
  {
    "code": "CP_CALL",
    "name": "Cost per booked call",
    "group": "Cost",
    "funnelStage": "Service",
    "unit": "Rs",
    "formula": "spend / booked calls",
    "direction": "Down = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Spend + scheduler",
    "platform": "Ad spend + CRM",
    "meaning": "What you pay to book one sales call.",
    "metaOnly": false
  },
  {
    "code": "SHOW_RATE",
    "name": "Call show-up rate",
    "group": "Funnel",
    "funnelStage": "Service",
    "unit": "%",
    "formula": "calls attended / calls booked x 100",
    "direction": "Up = good",
    "tier": "Calculated",
    "priority": "P1",
    "source": "Scheduler / CRM",
    "platform": "Calendly / CRM",
    "meaning": "Share of booked calls where the person showed up.",
    "metaOnly": false
  }
];
