// Money Map: a standalone, shareable HTML page of where the ad budget goes BY OPTIMISATION EVENT and what it
// returns. A media buyer can open it or send it to a client - a plain-English P&L by objective. Pure +
// deterministic, every dynamic string HTML-escaped (no injection), self-contained (inline CSS). Built from the
// same EventRoi rows the cockpit card shows, so the numbers always agree. ROI is shown only where the event
// makes real revenue; awareness events show n/a - never a fabricated return.

import type { EventRoi } from "./event-roi.ts";
import { eventBleedSummary, eventSpendSplit } from "./event-roi.ts";

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const inr = (n: number) => "Rs " + Math.round(n).toLocaleString("en-IN");
const title = (s: string) => s.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());

export function eventMoneyMapHtml(rows: EventRoi[], opts?: { accountName?: string; window?: string }): string {
  const who = `${opts?.accountName ?? "Your account"}${opts?.window ? ` - ${opts.window}` : ""}`;
  const split = eventSpendSplit(rows);
  const bleed = eventBleedSummary(rows);

  const roiCell = (e: EventRoi) => {
    if (!e.material) return `<span class="muted">too small to judge</span>`;
    if (e.roiPct === null) return `<span class="muted">n/a - no revenue</span>`;
    const cls = e.roiPct >= 0 ? "good" : "bad";
    return `<span class="${cls}">${e.roiPct >= 0 ? "+" : ""}${e.roiPct}%</span>${e.thinSample ? ` <span class="tag">directional</span>` : ""}`;
  };

  const bodyRows = rows
    .map(
      (e) =>
        `<tr><td>${esc(title(e.event))}</td><td class="num">${esc(inr(e.spendRs))}</td><td class="num">${e.spendSharePct}%</td><td class="num">${e.revenueRs > 0 ? esc(inr(e.revenueRs)) : "-"}</td><td class="num">${roiCell(e)}</td></tr>`,
    )
    .join("");

  const summary = split
    ? `<p class="summary">${esc(inr(split.totalRs))} total &middot; ${split.revenuePct}% on revenue events &middot; ${split.awarenessPct}% on awareness.</p>`
    : "";
  const reallocate = bleed ? `<div class="callout"><strong>Reallocate:</strong> ${esc(bleed.line)}</div>` : "";

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Money map - ${esc(who)}</title><style>
:root{--bg:#f7f7f7;--surface:#fff;--ink:#252525;--muted:#6b6b6b;--accent:#0a66c2;--hairline:#e4e4e4;--good:#0f8a4d;--bad:#c0392b;--warnbg:#fbf1df;--warnink:#b06b00}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;padding:32px}
.wrap{max-width:760px;margin:0 auto}.eyebrow{font-size:12px;letter-spacing:.04em;text-transform:uppercase;color:var(--accent);font-weight:600}
h1{font-size:24px;font-weight:400;margin:4px 0 2px}.for{color:var(--muted);font-size:13px;margin-bottom:16px}
.summary{font-size:15px;font-weight:500;margin:0 0 16px}
.callout{background:var(--warnbg);color:var(--warnink);border-radius:10px;padding:12px 14px;font-size:14px;margin-bottom:20px}
table{width:100%;border-collapse:collapse;background:var(--surface);border:1px solid var(--hairline);border-radius:12px;overflow:hidden}
th,td{text-align:left;padding:10px 14px;border-top:1px solid var(--hairline);font-size:14px}th{background:#fafafa;font-size:11px;letter-spacing:.03em;text-transform:uppercase;color:var(--muted);border-top:0}
.num{text-align:right;font-variant-numeric:tabular-nums}.good{color:var(--good);font-weight:600}.bad{color:var(--bad);font-weight:600}.muted{color:var(--muted)}
.tag{font-size:10px;background:#eee;color:var(--muted);border-radius:99px;padding:1px 6px}
.foot{color:var(--muted);font-size:12px;margin-top:20px;text-align:center}
.rubric{color:var(--muted);font-size:12px;margin-top:14px;line-height:1.5}
</style></head><body><div class="wrap"><div class="eyebrow">AdScale</div><h1>Money map by optimisation event</h1><div class="for">${esc(who)}</div>${summary}${reallocate}
<table><thead><tr><th>Event</th><th class="num">Spend</th><th class="num">Share</th><th class="num">Revenue</th><th class="num">ROI</th></tr></thead><tbody>${bodyRows || '<tr><td colspan="5" class="muted">No event data yet - sync your ad-set optimisation events.</td></tr>'}</tbody></table>
<div class="rubric">ROI = (revenue - spend) / spend, shown only where the event produces real purchase revenue. Events with no rupee revenue (Reach, Profile visit) show n/a - judged on cost per result, not ROI. "directional" = ROI on very few purchases (not yet stable). Nothing here is estimated.</div>
<div class="foot">Generated by AdScale from your connected account.</div></div></body></html>`;
}
